### ISSUE TITLE
Create gamerule to disable explosion damage to terrain

### ISSUE THREAD

**Issue by PopeTrennadict** [lstwo/PipebombInTheMail#1]
Feature suggestion:
A gamerule that would disable explosive damage to terrain, so that only the player dies without property damage would make for much more humorous encounters. Recipients would be less salty about getting blown up. You could call the gamerule "doPropertyDamage" or something similar.

**Comment by lstwo** [comment]
has been added now. will be ported to 1.19.4 and uploaded to modrinth

**Comment by lstwo** [comment]
now uploaded to modrinth
